#ifndef __TIMCommsPrefs__
#define __TIMCommsPrefs__

/**
@file
Subclass of TIMCommsPrefs, which is generated by wxFormBuilder.
*/

#include "TIMCommsPreferences.h"

/** Implementing TIMCommsPrefs */
class TIMCommsPrefs : public TIMCommsPreferences
{
protected:
	// Handlers for TIMCommsPrefs events.
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	TIMCommsPrefs( wxWindow* parent );
};

#endif // __TIMCommsPrefs__
